#!/bin/bash
#
# Create SSL certificates
#

DAYS=730
if [$# -eq 2] 
then 
        CERTPAHT="$2"
else
        CERTPATH="./"
fi


if [ $# -ne 2  ] or [ $1 == "help" ] or [ $2 == "--help"] ; then
echo "Usage: $0 [host.domain] PATH
     if $2 PATH is not mentioned it will createa cert in ./
     if $2 PATH is missing, it will be created"
exit 10
fi

if [ ! -d $CERTPATH ] 
        then
                mkdir -p $CERTPATH
fi

echo "Certificate for $1"

(
echo "CZ"
echo "BRNO"
echo "BRNO"
echo "ITLEAD"
echo "ITLEAD"
echo $1
echo "webmaster@$1"
echo
echo
) |
openssl req -new -nodes -keyout $CERTPATH/$1.key -out $CERTPATH/$1.req -days $DAYS

